export const BOOK_LIST_REQUEST = "BOOK_LIST_REQUEST";
export const BOOK_LIST_SUCCESS = "BOOK_LIST_SUCCESS";
export const BOOK_LIST_FAIL = "BOOK_LIST_FAIL";

export const AUTHOR_LIST_REQUEST = "AUTHOR_LIST_REQUEST";
export const AUTHOR_LIST_SUCCESS = "AUTHOR_LIST_SUCCESS";
export const AUTHOR_LIST_FAIL = "AUTHOR_LIST_FAIL";

export const CATEGORY_LIST_REQUEST = "CATEGORY_LIST_REQUEST";
export const CATEGORY_LIST_SUCCESS = "CATEGORY_LIST_SUCCESS";
export const CATEGORY_LIST_FAIL = "CATEGORY_LIST_FAIL";

export const BOOK_DETAILS_REQUEST = "BOOK_DETAILS_REQUEST";
export const BOOK_DETAILS_SUCCESS = "BOOK_DETAILS_SUCCESS";
export const BOOK_DETAILS_FAIL = "BOOK_DETAILS_FAIL";

export const BOOK_DELETE_REQUEST = "BOOK_DELETE_REQUEST";
export const BOOK_DELETE_SUCCESS = "BOOK_DELETE_SUCCESS";
export const BOOK_DELETE_FAIL = "BOOK_DELETE_FAIL";

export const BOOK_CREATE_REQUEST = "BOOK_CREATE_REQUEST";
export const BOOK_CREATE_SUCCESS = "BOOK_CREATE_SUCCESS";
export const BOOK_CREATE_FAIL = "BOOK_CREATE_FAIL";
export const BOOK_CREATE_RESET = "BOOK_CREATE_RESET";

export const BOOK_UPDATE_REQUEST = "BOOK_UPDATE_REQUEST";
export const BOOK_UPDATE_SUCCESS = "BOOK_UPDATE_SUCCESS";
export const BOOK_UPDATE_FAIL = "BOOK_UPDATE_FAIL";
export const BOOK_UPDATE_RESET = "BOOK_UPDATE_RESET";

export const BOOK_CREATE_REVIEW_REQUEST = "BOOK_CREATE_REVIEW_REQUEST";
export const BOOK_CREATE_REVIEW_SUCCESS = "BOOK_CREATE_REVIEW_SUCCESS";
export const BOOK_CREATE_REVIEW_FAIL = "BOOK_CREATE_REVIEW_FAIL";
export const BOOK_CREATE_REVIEW_RESET = "BOOK_CREATE_REVIEW_RESET";

export const BOOK_TOP_REQUEST = "BOOK_TOP_REQUEST";
export const BOOK_TOP_SUCCESS = "BOOK_TOP_SUCCESS";
export const BOOK_TOP_FAIL = "BOOK_TOP_FAIL";

export const MY_BOOK_REQUEST = "MY_BOOK_REQUEST";
export const MY_BOOK_SUCCESS = "MY_BOOK_SUCCESS";
export const MY_BOOK_FAIL = "MY_BOOK_FAIL";


export const BOOK_REQUEST_REQUEST = "BOOK_REQUEST_REQUEST";
export const BOOK_REQUEST_SUCCESS = "BOOK_REQUEST_SUCCESS";
export const BOOK_REQUEST_FAIL = "BOOK_REQUEST_FAIL";
export const BOOK_REQUEST_RESET = "BOOK_REQUEST_RESET";

export const NOTIFICATION_REQUEST = "NOTIFICATION_REQUEST";
export const NOTIFICATION_SUCCESS = "NOTIFICATION_SUCCESS";
export const NOTIFICATION_FAIL = "NOTIFICATION_FAIL";

export const MARK_NOTIFICATION_REQUEST = "MARK_NOTIFICATION_REQUEST";
export const MARK_NOTIFICATION_SUCCESS = "MARK_NOTIFICATION_SUCCESS";
export const MARK_NOTIFICATION_FAIL = "MARK_NOTIFICATION_FAIL";


